# Generated by Django 5.1.2 on 2024-10-30 17:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_alter_user_managers_user_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("video", models.FileField(upload_to="videos")),
                (
                    "subtitle",
                    models.FileField(blank=True, null=True, upload_to="subtitles"),
                ),
                (
                    "thumbnail",
                    models.ImageField(blank=True, null=True, upload_to="thumbnail"),
                ),
                ("title", models.CharField(max_length=200)),
            ],
        ),
    ]
